// Code generated by protoc-gen-go-hi. DO NOT EDIT.
// versions:

package greeters

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/GodWY/hip/service"
)

// generated http method
func registerGreeterHttpHandler(srv service.Service, srvs GreeterHttpHandler) {
	group := srv.Router("greeter")
	group.GET("/api/v1/sayhello", srvs.SayHello)
	group.POST("/api/v1/askhello", srvs.AskHello)
}

var TGreeter Greeter

func RegisterGreeterHttpHandler(srv service.Service, srvs Greeter) {
	tmp := new(xxx_Greeter)
	registerGreeterHttpHandler(srv, tmp)
	TGreeter = srvs
}

type Greeter interface {
	SayHello(ctx *gin.Context, in *SayHelloRequest) (out *SayHelloResponse, err error)
	AskHello(ctx *gin.Context, in *AskHelloRequest) (out *AskHelloResponse, err error)
}

// generated http handle
type GreeterHttpHandler interface {
	SayHello(ctx *gin.Context)
	AskHello(ctx *gin.Context)
}

type xxx_Greeter struct {
}

func (xx *xxx_Greeter) SayHello(ctx *gin.Context) {
	req := &SayHelloRequest{}
	if ok := ctx.Bind(req); ok != nil {
		ctx.JSON(http.StatusOK, "bind error")
		return
	}
	rsp, err := TGreeter.SayHello(ctx, req)
	if err != nil {
		ctx.JSON(http.StatusOK, err.Error())
		return
	}
	ctx.JSON(http.StatusOK, rsp)
}

func (xx *xxx_Greeter) AskHello(ctx *gin.Context) {
	req := &AskHelloRequest{}
	if ok := ctx.Bind(req); ok != nil {
		ctx.JSON(http.StatusOK, "bind error")
		return
	}
	rsp, err := TGreeter.AskHello(ctx, req)
	if err != nil {
		ctx.JSON(http.StatusOK, err.Error())
		return
	}
	ctx.JSON(http.StatusOK, rsp)
}
